{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests, json\n",
    "import pandas as pd\n",
    "from pandas.io.json import json_normalize\n",
    "def buildUrl(page, pagesize, tagged):\n",
    "    return 'https://api.stackexchange.com/2.2/questions?order=desc&sort=activity&site=stackoverflow&page={0}&pagesize={1}&tagged={2}'.format(page, pagesize, tagged)\n",
    "\n",
    "pagesize = 20\n",
    "tagged = 'python'\n",
    "linesQuan = 20\n",
    "has_more = True\n",
    "page = 1\n",
    "lines = 0\n",
    "\n",
    "while (lines <= linesQuan and has_more):\n",
    "    result = requests.get(buildUrl(page, pagesize, tagged))\n",
    "    if result.status_code != 200:\n",
    "         break\n",
    "    else :  \n",
    "        if lines < linesQuan:\n",
    "            df = pd.DataFrame.from_dict(json_normalize(result.json().get('items')), orient='columns')\n",
    "        lines = lines + 1\n",
    "    has_more = result.json().get('has_more')               \n",
    "    page = page + 1\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>accepted_answer_id</th>\n",
       "      <th>answer_count</th>\n",
       "      <th>closed_date</th>\n",
       "      <th>closed_reason</th>\n",
       "      <th>creation_date</th>\n",
       "      <th>is_answered</th>\n",
       "      <th>last_activity_date</th>\n",
       "      <th>last_edit_date</th>\n",
       "      <th>link</th>\n",
       "      <th>owner.accept_rate</th>\n",
       "      <th>...</th>\n",
       "      <th>owner.link</th>\n",
       "      <th>owner.profile_image</th>\n",
       "      <th>owner.reputation</th>\n",
       "      <th>owner.user_id</th>\n",
       "      <th>owner.user_type</th>\n",
       "      <th>question_id</th>\n",
       "      <th>score</th>\n",
       "      <th>tags</th>\n",
       "      <th>title</th>\n",
       "      <th>view_count</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526124535</td>\n",
       "      <td>False</td>\n",
       "      <td>1526125972</td>\n",
       "      <td>1.526126e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50305725/c...</td>\n",
       "      <td>27.0</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/1973779/rahul-raj</td>\n",
       "      <td>https://i.stack.imgur.com/Fuaoo.jpg?s=128&amp;g=1</td>\n",
       "      <td>988</td>\n",
       "      <td>1973779</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305725</td>\n",
       "      <td>1</td>\n",
       "      <td>[python, anaconda, conda]</td>\n",
       "      <td>CondaHTTPError: HTTP 000 CONNECTION FAILED for...</td>\n",
       "      <td>12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>NaN</td>\n",
       "      <td>1</td>\n",
       "      <td>1.526150e+09</td>\n",
       "      <td>off-topic</td>\n",
       "      <td>1526111574</td>\n",
       "      <td>False</td>\n",
       "      <td>1526125873</td>\n",
       "      <td>1.526114e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50304053/p...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9642904/ruchit...</td>\n",
       "      <td>https://lh6.googleusercontent.com/-_Y1FAw47_mk...</td>\n",
       "      <td>1</td>\n",
       "      <td>9642904</td>\n",
       "      <td>registered</td>\n",
       "      <td>50304053</td>\n",
       "      <td>-3</td>\n",
       "      <td>[python, pandas, csv]</td>\n",
       "      <td>pandas not reading first 4 columns of CSV file</td>\n",
       "      <td>45</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526121348</td>\n",
       "      <td>False</td>\n",
       "      <td>1526125780</td>\n",
       "      <td>1.526126e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50305287/h...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/7284441/user72...</td>\n",
       "      <td>https://www.gravatar.com/avatar/12627b44a14b99...</td>\n",
       "      <td>4</td>\n",
       "      <td>7284441</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305287</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, flask]</td>\n",
       "      <td>How Flask implements slides</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>50305569.0</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526120442</td>\n",
       "      <td>True</td>\n",
       "      <td>1526125764</td>\n",
       "      <td>1.526126e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50305167/h...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/5657159/trdngy</td>\n",
       "      <td>https://www.gravatar.com/avatar/86cea357c70d3a...</td>\n",
       "      <td>59</td>\n",
       "      <td>5657159</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305167</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, tensorflow]</td>\n",
       "      <td>How to print more than 3 values inside a tenso...</td>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>NaN</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526120686</td>\n",
       "      <td>False</td>\n",
       "      <td>1526125688</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://stackoverflow.com/questions/50305218/h...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9780230/lofi</td>\n",
       "      <td>https://i.stack.imgur.com/LmokJ.jpg?s=128&amp;g=1</td>\n",
       "      <td>1</td>\n",
       "      <td>9780230</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305218</td>\n",
       "      <td>0</td>\n",
       "      <td>[python]</td>\n",
       "      <td>How to &amp;quot;Select&amp;quot; a correct user answe...</td>\n",
       "      <td>17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526091622</td>\n",
       "      <td>False</td>\n",
       "      <td>1526125625</td>\n",
       "      <td>1.526126e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50302316/p...</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/6905646/zebralamy</td>\n",
       "      <td>https://www.gravatar.com/avatar/8a8d5a5996fabc...</td>\n",
       "      <td>61</td>\n",
       "      <td>6905646</td>\n",
       "      <td>registered</td>\n",
       "      <td>50302316</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, web-scraping, beautifulsoup, wkhtmlto...</td>\n",
       "      <td>pdfkit returns blank pdf on specific sites. (p...</td>\n",
       "      <td>14</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>50305844.0</td>\n",
       "      <td>2</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526124627</td>\n",
       "      <td>True</td>\n",
       "      <td>1526125610</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://stackoverflow.com/questions/50305739/h...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/5680305/aiden-...</td>\n",
       "      <td>https://graph.facebook.com/1673975559555818/pi...</td>\n",
       "      <td>13</td>\n",
       "      <td>5680305</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305739</td>\n",
       "      <td>2</td>\n",
       "      <td>[python]</td>\n",
       "      <td>How to replace an integer with a different cla...</td>\n",
       "      <td>29</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>NaN</td>\n",
       "      <td>1</td>\n",
       "      <td>1.526119e+09</td>\n",
       "      <td>off-topic</td>\n",
       "      <td>1526118288</td>\n",
       "      <td>True</td>\n",
       "      <td>1526125361</td>\n",
       "      <td>1.526119e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50304874/h...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/8438769/varun-...</td>\n",
       "      <td>https://www.gravatar.com/avatar/4797210380ba82...</td>\n",
       "      <td>6</td>\n",
       "      <td>8438769</td>\n",
       "      <td>registered</td>\n",
       "      <td>50304874</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, python-3.x]</td>\n",
       "      <td>How can I break the loop before printing 506?</td>\n",
       "      <td>23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>NaN</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526123595</td>\n",
       "      <td>False</td>\n",
       "      <td>1526125264</td>\n",
       "      <td>1.526124e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50305601/p...</td>\n",
       "      <td>91.0</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/1727392/duhaime</td>\n",
       "      <td>https://i.stack.imgur.com/KP9Ia.jpg?s=128&amp;g=1</td>\n",
       "      <td>5748</td>\n",
       "      <td>1727392</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305601</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, redis, celery]</td>\n",
       "      <td>Python: delete all celery workers</td>\n",
       "      <td>16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526125174</td>\n",
       "      <td>False</td>\n",
       "      <td>1526125174</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://stackoverflow.com/questions/50305821/p...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9780285/j-l-g</td>\n",
       "      <td>https://www.gravatar.com/avatar/aa78d559a3322e...</td>\n",
       "      <td>1</td>\n",
       "      <td>9780285</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305821</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, heroku, python-requests, telegram-bot...</td>\n",
       "      <td>Python telegram bot deployed on heroku failed ...</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>NaN</td>\n",
       "      <td>4</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526124813</td>\n",
       "      <td>True</td>\n",
       "      <td>1526125156</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://stackoverflow.com/questions/50305764/h...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9780434/chid0ry</td>\n",
       "      <td>https://www.gravatar.com/avatar/a11d213823b4f7...</td>\n",
       "      <td>1</td>\n",
       "      <td>9780434</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305764</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, syntax-error]</td>\n",
       "      <td>How to execute Python scripts with python command</td>\n",
       "      <td>25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>NaN</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526098805</td>\n",
       "      <td>False</td>\n",
       "      <td>1526125132</td>\n",
       "      <td>1.526125e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50302807/p...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9779470/leila-...</td>\n",
       "      <td>https://lh4.googleusercontent.com/-Fnp1XK2gSOE...</td>\n",
       "      <td>9</td>\n",
       "      <td>9779470</td>\n",
       "      <td>registered</td>\n",
       "      <td>50302807</td>\n",
       "      <td>-1</td>\n",
       "      <td>[python]</td>\n",
       "      <td>python keeps running previous modules instead ...</td>\n",
       "      <td>25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526112778</td>\n",
       "      <td>False</td>\n",
       "      <td>1526125129</td>\n",
       "      <td>1.526125e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50304178/h...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9779932/helen</td>\n",
       "      <td>https://www.gravatar.com/avatar/7066210f2c7827...</td>\n",
       "      <td>1</td>\n",
       "      <td>9779932</td>\n",
       "      <td>registered</td>\n",
       "      <td>50304178</td>\n",
       "      <td>-1</td>\n",
       "      <td>[python, matrix, latex]</td>\n",
       "      <td>how to plot a latex matrix dynamically in python</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526075112</td>\n",
       "      <td>True</td>\n",
       "      <td>1526125095</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://stackoverflow.com/questions/50300679/p...</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/6677611/commis...</td>\n",
       "      <td>https://graph.facebook.com/10157455517365495/p...</td>\n",
       "      <td>140</td>\n",
       "      <td>6677611</td>\n",
       "      <td>registered</td>\n",
       "      <td>50300679</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, pandas, dataframe]</td>\n",
       "      <td>Pandas Dataframe Autofill</td>\n",
       "      <td>28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>NaN</td>\n",
       "      <td>2</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526033516</td>\n",
       "      <td>True</td>\n",
       "      <td>1526124794</td>\n",
       "      <td>1.526034e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50290009/f...</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/2607201/dca</td>\n",
       "      <td>https://i.stack.imgur.com/bwnDh.jpg?s=128&amp;g=1</td>\n",
       "      <td>636</td>\n",
       "      <td>2607201</td>\n",
       "      <td>registered</td>\n",
       "      <td>50290009</td>\n",
       "      <td>5</td>\n",
       "      <td>[python, string]</td>\n",
       "      <td>Find the lowercase (un-shifted) form of symbols</td>\n",
       "      <td>30</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>50305748.0</td>\n",
       "      <td>1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526124323</td>\n",
       "      <td>True</td>\n",
       "      <td>1526124723</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://stackoverflow.com/questions/50305702/d...</td>\n",
       "      <td>50.0</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9046380/marcus...</td>\n",
       "      <td>https://www.gravatar.com/avatar/e2a3901a83058a...</td>\n",
       "      <td>37</td>\n",
       "      <td>9046380</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305702</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, django, templates, view]</td>\n",
       "      <td>Django - creating a main page without an exten...</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>50304586.0</td>\n",
       "      <td>2</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526115386</td>\n",
       "      <td>True</td>\n",
       "      <td>1526124495</td>\n",
       "      <td>1.526124e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50304483/p...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9135962/zhao-c...</td>\n",
       "      <td>https://www.gravatar.com/avatar/13d13ad7254a4d...</td>\n",
       "      <td>5</td>\n",
       "      <td>9135962</td>\n",
       "      <td>registered</td>\n",
       "      <td>50304483</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, pprint]</td>\n",
       "      <td>Printing a list vertically with pprint</td>\n",
       "      <td>25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526124290</td>\n",
       "      <td>False</td>\n",
       "      <td>1526124290</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://stackoverflow.com/questions/50305696/p...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9751224/mohame...</td>\n",
       "      <td>https://www.gravatar.com/avatar/3ed553e069e586...</td>\n",
       "      <td>6</td>\n",
       "      <td>9751224</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305696</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, loops, tkinter]</td>\n",
       "      <td>python text box new line is not working for me</td>\n",
       "      <td>21</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526124111</td>\n",
       "      <td>False</td>\n",
       "      <td>1526124111</td>\n",
       "      <td>NaN</td>\n",
       "      <td>https://stackoverflow.com/questions/50305670/a...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/7793070/dicama...</td>\n",
       "      <td>https://www.gravatar.com/avatar/92c34438625a7e...</td>\n",
       "      <td>1</td>\n",
       "      <td>7793070</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305670</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, python-asyncio, discord.py]</td>\n",
       "      <td>Asyncio &amp;quot;RuntimeError: Event loop is clos...</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1526120488</td>\n",
       "      <td>False</td>\n",
       "      <td>1526124071</td>\n",
       "      <td>1.526124e+09</td>\n",
       "      <td>https://stackoverflow.com/questions/50305181/h...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>https://stackoverflow.com/users/9780282/queueo...</td>\n",
       "      <td>https://www.gravatar.com/avatar/241e6d1a1e0fa1...</td>\n",
       "      <td>4</td>\n",
       "      <td>9780282</td>\n",
       "      <td>registered</td>\n",
       "      <td>50305181</td>\n",
       "      <td>0</td>\n",
       "      <td>[python, node.js, database, firebase]</td>\n",
       "      <td>How to route functions with parameters in pyth...</td>\n",
       "      <td>14</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>20 rows × 21 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "    accepted_answer_id  answer_count   closed_date closed_reason  \\\n",
       "0                  NaN             0           NaN           NaN   \n",
       "1                  NaN             1  1.526150e+09     off-topic   \n",
       "2                  NaN             0           NaN           NaN   \n",
       "3           50305569.0             1           NaN           NaN   \n",
       "4                  NaN             1           NaN           NaN   \n",
       "5                  NaN             0           NaN           NaN   \n",
       "6           50305844.0             2           NaN           NaN   \n",
       "7                  NaN             1  1.526119e+09     off-topic   \n",
       "8                  NaN             1           NaN           NaN   \n",
       "9                  NaN             0           NaN           NaN   \n",
       "10                 NaN             4           NaN           NaN   \n",
       "11                 NaN             1           NaN           NaN   \n",
       "12                 NaN             0           NaN           NaN   \n",
       "13                 NaN             2           NaN           NaN   \n",
       "14                 NaN             2           NaN           NaN   \n",
       "15          50305748.0             1           NaN           NaN   \n",
       "16          50304586.0             2           NaN           NaN   \n",
       "17                 NaN             0           NaN           NaN   \n",
       "18                 NaN             0           NaN           NaN   \n",
       "19                 NaN             0           NaN           NaN   \n",
       "\n",
       "    creation_date  is_answered  last_activity_date  last_edit_date  \\\n",
       "0      1526124535        False          1526125972    1.526126e+09   \n",
       "1      1526111574        False          1526125873    1.526114e+09   \n",
       "2      1526121348        False          1526125780    1.526126e+09   \n",
       "3      1526120442         True          1526125764    1.526126e+09   \n",
       "4      1526120686        False          1526125688             NaN   \n",
       "5      1526091622        False          1526125625    1.526126e+09   \n",
       "6      1526124627         True          1526125610             NaN   \n",
       "7      1526118288         True          1526125361    1.526119e+09   \n",
       "8      1526123595        False          1526125264    1.526124e+09   \n",
       "9      1526125174        False          1526125174             NaN   \n",
       "10     1526124813         True          1526125156             NaN   \n",
       "11     1526098805        False          1526125132    1.526125e+09   \n",
       "12     1526112778        False          1526125129    1.526125e+09   \n",
       "13     1526075112         True          1526125095             NaN   \n",
       "14     1526033516         True          1526124794    1.526034e+09   \n",
       "15     1526124323         True          1526124723             NaN   \n",
       "16     1526115386         True          1526124495    1.526124e+09   \n",
       "17     1526124290        False          1526124290             NaN   \n",
       "18     1526124111        False          1526124111             NaN   \n",
       "19     1526120488        False          1526124071    1.526124e+09   \n",
       "\n",
       "                                                 link  owner.accept_rate  \\\n",
       "0   https://stackoverflow.com/questions/50305725/c...               27.0   \n",
       "1   https://stackoverflow.com/questions/50304053/p...                NaN   \n",
       "2   https://stackoverflow.com/questions/50305287/h...                NaN   \n",
       "3   https://stackoverflow.com/questions/50305167/h...                NaN   \n",
       "4   https://stackoverflow.com/questions/50305218/h...                NaN   \n",
       "5   https://stackoverflow.com/questions/50302316/p...              100.0   \n",
       "6   https://stackoverflow.com/questions/50305739/h...                NaN   \n",
       "7   https://stackoverflow.com/questions/50304874/h...                NaN   \n",
       "8   https://stackoverflow.com/questions/50305601/p...               91.0   \n",
       "9   https://stackoverflow.com/questions/50305821/p...                NaN   \n",
       "10  https://stackoverflow.com/questions/50305764/h...                NaN   \n",
       "11  https://stackoverflow.com/questions/50302807/p...                NaN   \n",
       "12  https://stackoverflow.com/questions/50304178/h...                NaN   \n",
       "13  https://stackoverflow.com/questions/50300679/p...              100.0   \n",
       "14  https://stackoverflow.com/questions/50290009/f...              100.0   \n",
       "15  https://stackoverflow.com/questions/50305702/d...               50.0   \n",
       "16  https://stackoverflow.com/questions/50304483/p...                NaN   \n",
       "17  https://stackoverflow.com/questions/50305696/p...                NaN   \n",
       "18  https://stackoverflow.com/questions/50305670/a...                NaN   \n",
       "19  https://stackoverflow.com/questions/50305181/h...                NaN   \n",
       "\n",
       "      ...                                             owner.link  \\\n",
       "0     ...      https://stackoverflow.com/users/1973779/rahul-raj   \n",
       "1     ...      https://stackoverflow.com/users/9642904/ruchit...   \n",
       "2     ...      https://stackoverflow.com/users/7284441/user72...   \n",
       "3     ...         https://stackoverflow.com/users/5657159/trdngy   \n",
       "4     ...           https://stackoverflow.com/users/9780230/lofi   \n",
       "5     ...      https://stackoverflow.com/users/6905646/zebralamy   \n",
       "6     ...      https://stackoverflow.com/users/5680305/aiden-...   \n",
       "7     ...      https://stackoverflow.com/users/8438769/varun-...   \n",
       "8     ...        https://stackoverflow.com/users/1727392/duhaime   \n",
       "9     ...          https://stackoverflow.com/users/9780285/j-l-g   \n",
       "10    ...        https://stackoverflow.com/users/9780434/chid0ry   \n",
       "11    ...      https://stackoverflow.com/users/9779470/leila-...   \n",
       "12    ...          https://stackoverflow.com/users/9779932/helen   \n",
       "13    ...      https://stackoverflow.com/users/6677611/commis...   \n",
       "14    ...            https://stackoverflow.com/users/2607201/dca   \n",
       "15    ...      https://stackoverflow.com/users/9046380/marcus...   \n",
       "16    ...      https://stackoverflow.com/users/9135962/zhao-c...   \n",
       "17    ...      https://stackoverflow.com/users/9751224/mohame...   \n",
       "18    ...      https://stackoverflow.com/users/7793070/dicama...   \n",
       "19    ...      https://stackoverflow.com/users/9780282/queueo...   \n",
       "\n",
       "                                  owner.profile_image owner.reputation  \\\n",
       "0       https://i.stack.imgur.com/Fuaoo.jpg?s=128&g=1              988   \n",
       "1   https://lh6.googleusercontent.com/-_Y1FAw47_mk...                1   \n",
       "2   https://www.gravatar.com/avatar/12627b44a14b99...                4   \n",
       "3   https://www.gravatar.com/avatar/86cea357c70d3a...               59   \n",
       "4       https://i.stack.imgur.com/LmokJ.jpg?s=128&g=1                1   \n",
       "5   https://www.gravatar.com/avatar/8a8d5a5996fabc...               61   \n",
       "6   https://graph.facebook.com/1673975559555818/pi...               13   \n",
       "7   https://www.gravatar.com/avatar/4797210380ba82...                6   \n",
       "8       https://i.stack.imgur.com/KP9Ia.jpg?s=128&g=1             5748   \n",
       "9   https://www.gravatar.com/avatar/aa78d559a3322e...                1   \n",
       "10  https://www.gravatar.com/avatar/a11d213823b4f7...                1   \n",
       "11  https://lh4.googleusercontent.com/-Fnp1XK2gSOE...                9   \n",
       "12  https://www.gravatar.com/avatar/7066210f2c7827...                1   \n",
       "13  https://graph.facebook.com/10157455517365495/p...              140   \n",
       "14      https://i.stack.imgur.com/bwnDh.jpg?s=128&g=1              636   \n",
       "15  https://www.gravatar.com/avatar/e2a3901a83058a...               37   \n",
       "16  https://www.gravatar.com/avatar/13d13ad7254a4d...                5   \n",
       "17  https://www.gravatar.com/avatar/3ed553e069e586...                6   \n",
       "18  https://www.gravatar.com/avatar/92c34438625a7e...                1   \n",
       "19  https://www.gravatar.com/avatar/241e6d1a1e0fa1...                4   \n",
       "\n",
       "    owner.user_id  owner.user_type question_id  score  \\\n",
       "0         1973779       registered    50305725      1   \n",
       "1         9642904       registered    50304053     -3   \n",
       "2         7284441       registered    50305287      0   \n",
       "3         5657159       registered    50305167      0   \n",
       "4         9780230       registered    50305218      0   \n",
       "5         6905646       registered    50302316      0   \n",
       "6         5680305       registered    50305739      2   \n",
       "7         8438769       registered    50304874      0   \n",
       "8         1727392       registered    50305601      0   \n",
       "9         9780285       registered    50305821      0   \n",
       "10        9780434       registered    50305764      0   \n",
       "11        9779470       registered    50302807     -1   \n",
       "12        9779932       registered    50304178     -1   \n",
       "13        6677611       registered    50300679      0   \n",
       "14        2607201       registered    50290009      5   \n",
       "15        9046380       registered    50305702      0   \n",
       "16        9135962       registered    50304483      0   \n",
       "17        9751224       registered    50305696      0   \n",
       "18        7793070       registered    50305670      0   \n",
       "19        9780282       registered    50305181      0   \n",
       "\n",
       "                                                 tags  \\\n",
       "0                           [python, anaconda, conda]   \n",
       "1                               [python, pandas, csv]   \n",
       "2                                     [python, flask]   \n",
       "3                                [python, tensorflow]   \n",
       "4                                            [python]   \n",
       "5   [python, web-scraping, beautifulsoup, wkhtmlto...   \n",
       "6                                            [python]   \n",
       "7                                [python, python-3.x]   \n",
       "8                             [python, redis, celery]   \n",
       "9   [python, heroku, python-requests, telegram-bot...   \n",
       "10                             [python, syntax-error]   \n",
       "11                                           [python]   \n",
       "12                            [python, matrix, latex]   \n",
       "13                        [python, pandas, dataframe]   \n",
       "14                                   [python, string]   \n",
       "15                  [python, django, templates, view]   \n",
       "16                                   [python, pprint]   \n",
       "17                           [python, loops, tkinter]   \n",
       "18               [python, python-asyncio, discord.py]   \n",
       "19              [python, node.js, database, firebase]   \n",
       "\n",
       "                                                title view_count  \n",
       "0   CondaHTTPError: HTTP 000 CONNECTION FAILED for...         12  \n",
       "1      pandas not reading first 4 columns of CSV file         45  \n",
       "2                         How Flask implements slides         21  \n",
       "3   How to print more than 3 values inside a tenso...         15  \n",
       "4   How to &quot;Select&quot; a correct user answe...         17  \n",
       "5   pdfkit returns blank pdf on specific sites. (p...         14  \n",
       "6   How to replace an integer with a different cla...         29  \n",
       "7       How can I break the loop before printing 506?         23  \n",
       "8                   Python: delete all celery workers         16  \n",
       "9   Python telegram bot deployed on heroku failed ...         18  \n",
       "10  How to execute Python scripts with python command         25  \n",
       "11  python keeps running previous modules instead ...         25  \n",
       "12   how to plot a latex matrix dynamically in python         11  \n",
       "13                          Pandas Dataframe Autofill         28  \n",
       "14    Find the lowercase (un-shifted) form of symbols         30  \n",
       "15  Django - creating a main page without an exten...         20  \n",
       "16             Printing a list vertically with pprint         25  \n",
       "17     python text box new line is not working for me         21  \n",
       "18  Asyncio &quot;RuntimeError: Event loop is clos...         11  \n",
       "19  How to route functions with parameters in pyth...         14  \n",
       "\n",
       "[20 rows x 21 columns]"
      ]
     },
     "execution_count": 43,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head(20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "df['last_activity_date'] = pd.to_datetime(df['last_activity_date'], format='%d%b%Y:%H:%M:%S.%f') "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tags\n",
      "['python', 'python-3.x']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 8061956, 'user_type': 'registered', 'profile_image': 'https://i.stack.imgur.com/KZBNp.jpg?s=128&g=1', 'display_name': 'Emerdan', 'link': 'https://stackoverflow.com/users/8061956/emerdan'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "13\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526118683\n",
      "creation_date\n",
      "1526118488\n",
      "last_edit_date\n",
      "1526118683\n",
      "question_id\n",
      "50304901\n",
      "link\n",
      "https://stackoverflow.com/questions/50304901/python-3-install-location\n",
      "title\n",
      "Python 3 install location\n",
      "tags\n",
      "['python', 'python-3.x']\n",
      "owner\n",
      "{'reputation': 6, 'user_id': 8438769, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/4797210380ba8238e6a912366938ad9f?s=128&d=identicon&r=PG&f=1', 'display_name': 'Varun_Sharma', 'link': 'https://stackoverflow.com/users/8438769/varun-sharma'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "6\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526118637\n",
      "creation_date\n",
      "1526118288\n",
      "last_edit_date\n",
      "1526118637\n",
      "question_id\n",
      "50304874\n",
      "link\n",
      "https://stackoverflow.com/questions/50304874/how-can-i-break-the-loop-before-printing-506\n",
      "title\n",
      "How can I break the loop before printing 506?\n",
      "tags\n",
      "['python', 'text', 'mining']\n",
      "owner\n",
      "{'reputation': 34, 'user_id': 6486100, 'user_type': 'registered', 'profile_image': 'https://lh5.googleusercontent.com/-t4VI7Udn6zw/AAAAAAAAAAI/AAAAAAAAAH4/y5bdXSD0N3c/photo.jpg?sz=128', 'display_name': 'Prasand Kumar', 'link': 'https://stackoverflow.com/users/6486100/prasand-kumar'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "22\n",
      "closed_date\n",
      "1526111316\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526118589\n",
      "creation_date\n",
      "1526106819\n",
      "last_edit_date\n",
      "1526118589\n",
      "question_id\n",
      "50303542\n",
      "link\n",
      "https://stackoverflow.com/questions/50303542/efficient-way-of-processing-a-large-text-file-of-size-2-5-gb-line-by-line-using\n",
      "closed_reason\n",
      "unclear what you&#39;re asking\n",
      "title\n",
      "Efficient way of processing a large text file of size 2.5 gb Line-by-Line using python\n",
      "tags\n",
      "['python', 'selenium', 'dom', 'selenium-chromedriver']\n",
      "owner\n",
      "{'reputation': 112, 'user_id': 9137919, 'user_type': 'registered', 'profile_image': 'https://i.stack.imgur.com/6jrm7.jpg?s=128&g=1', 'display_name': 'Rubi Jihantoro', 'link': 'https://stackoverflow.com/users/9137919/rubi-jihantoro'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "76\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526118539\n",
      "creation_date\n",
      "1523842949\n",
      "question_id\n",
      "49848571\n",
      "link\n",
      "https://stackoverflow.com/questions/49848571/selenium-chromedriver-prevent-unexpected-alert-open-alert-text\n",
      "title\n",
      "selenium chromedriver prevent unexpected alert open: {Alert text : }\n",
      "tags\n",
      "['python', 'python-3.x', 'sqlalchemy']\n",
      "owner\n",
      "{'reputation': 1305, 'user_id': 3744747, 'user_type': 'registered', 'accept_rate': 38, 'profile_image': 'https://www.gravatar.com/avatar/be3e2dbd8f056a7244934fbe197f5b3b?s=128&d=identicon&r=PG', 'display_name': 'mehrdad-pedramfar', 'link': 'https://stackoverflow.com/users/3744747/mehrdad-pedramfar'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "7\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "2\n",
      "last_activity_date\n",
      "1526118526\n",
      "creation_date\n",
      "1526118352\n",
      "last_edit_date\n",
      "1526118526\n",
      "question_id\n",
      "50304880\n",
      "link\n",
      "https://stackoverflow.com/questions/50304880/filtering-or-of-multiple-between-in-sqlalchemy\n",
      "title\n",
      "Filtering or of multiple between in sqlalchemy\n",
      "tags\n",
      "['python', 'palindrome']\n",
      "owner\n",
      "{'reputation': 5, 'user_id': 7730660, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/eaf8f7f76ca33555c61a3989322d2a5e?s=128&d=identicon&r=PG&f=1', 'display_name': 'SHubHam', 'link': 'https://stackoverflow.com/users/7730660/shubham'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "9\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526118272\n",
      "creation_date\n",
      "1526118272\n",
      "question_id\n",
      "50304873\n",
      "link\n",
      "https://stackoverflow.com/questions/50304873/why-run-time-error-in-program\n",
      "title\n",
      "Why run time error in program?\n",
      "tags\n",
      "['python', 'excel']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 5397182, 'user_type': 'registered', 'profile_image': 'https://lh4.googleusercontent.com/-glK1MyUKFCU/AAAAAAAAAAI/AAAAAAAAAFg/HS8dJrHPLSo/photo.jpg?sz=128', 'display_name': 'Erix', 'link': 'https://stackoverflow.com/users/5397182/erix'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "6\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526118246\n",
      "creation_date\n",
      "1526118246\n",
      "question_id\n",
      "50304867\n",
      "link\n",
      "https://stackoverflow.com/questions/50304867/finding-a-repeated-value-in-excel-with-different-locations-in-a-excel-using-pyth\n",
      "title\n",
      "Finding a repeated value in excel with different locations in a excel using python\n",
      "tags\n",
      "['python', 'string', 'parsing', 'beautifulsoup']\n",
      "owner\n",
      "{'reputation': 2715, 'user_id': 2876236, 'user_type': 'registered', 'accept_rate': 62, 'profile_image': 'https://www.gravatar.com/avatar/9716bf63b6c9bc35262fa084f1c90ea5?s=128&d=identicon&r=PG&f=1', 'display_name': 'Andrew', 'link': 'https://stackoverflow.com/users/2876236/andrew'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "15\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "2\n",
      "last_activity_date\n",
      "1526118138\n",
      "creation_date\n",
      "1526116291\n",
      "question_id\n",
      "50304607\n",
      "link\n",
      "https://stackoverflow.com/questions/50304607/how-can-i-make-string-parsing-in-python-less-wieldy\n",
      "title\n",
      "How can I make string parsing in Python less wieldy?\n",
      "tags\n",
      "['python', 'command-line', 'access-denied', 'mrjob']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 6189157, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/df6fb8d48fbb845ab95ffbbf29e24b25?s=128&d=identicon&r=PG&f=1', 'display_name': 'Alura', 'link': 'https://stackoverflow.com/users/6189157/alura'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "8\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526118099\n",
      "creation_date\n",
      "1526117717\n",
      "last_edit_date\n",
      "1526118099\n",
      "question_id\n",
      "50304791\n",
      "link\n",
      "https://stackoverflow.com/questions/50304791/mrjob-windowserror-error-5-access-is-denied-windows-10\n",
      "title\n",
      "MrJob WindowsError: [Error 5] Access is denied Windows 10\n",
      "tags\n",
      "['python', 'cluster-computing', 'cluster-analysis']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 8087073, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/ba6c781f2b5639e00e535869ed80c766?s=128&d=identicon&r=PG&f=1', 'display_name': 'Filip', 'link': 'https://stackoverflow.com/users/8087073/filip'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "344\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526118066\n",
      "creation_date\n",
      "1509985105\n",
      "question_id\n",
      "47141314\n",
      "link\n",
      "https://stackoverflow.com/questions/47141314/clustering-with-kprototypes\n",
      "title\n",
      "Clustering with KPrototypes\n",
      "tags\n",
      "['python', 'list', 'sorting', 'math', 'matrix']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 9780023, 'user_type': 'registered', 'profile_image': 'https://lh6.googleusercontent.com/-oovWFLuW6rM/AAAAAAAAAAI/AAAAAAAAAUg/wIdc7qegSE8/photo.jpg?sz=128', 'display_name': 'Anuj Choudhary', 'link': 'https://stackoverflow.com/users/9780023/anuj-choudhary'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "17\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "-6\n",
      "last_activity_date\n",
      "1526117987\n",
      "creation_date\n",
      "1526115497\n",
      "last_edit_date\n",
      "1526116319\n",
      "question_id\n",
      "50304495\n",
      "link\n",
      "https://stackoverflow.com/questions/50304495/algorithm-for-ordering-lists-of-elements-by-their-sum-for-code-snippet-python\n",
      "title\n",
      "algorithm for ordering lists of elements by their sum ( For Code Snippet Python Is Preferred )\n",
      "tags\n",
      "['python', 'raspberry-pi', 'google-assistant-sdk']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 7122453, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/a11f917bc5d5f4724ba8e4a51dfb0ed8?s=128&d=identicon&r=PG', 'display_name': 'dev-1000', 'link': 'https://stackoverflow.com/users/7122453/dev-1000'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "19\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526117983\n",
      "creation_date\n",
      "1526036077\n",
      "last_edit_date\n",
      "1526117983\n",
      "question_id\n",
      "50290737\n",
      "link\n",
      "https://stackoverflow.com/questions/50290737/cant-upgrade-to-argparse-1-4-0-on-raspberry-pi\n",
      "title\n",
      "Cant upgrade to argparse 1.4.0 on raspberry pi\n",
      "tags\n",
      "['python', 'string', 'python-3.x', 'replace', 'iso-8859-15']\n",
      "owner\n",
      "{'reputation': 11, 'user_id': 8574270, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/2c41a8dd300bbb2c30e65739f748f417?s=128&d=identicon&r=PG&f=1', 'display_name': 'Jordi', 'link': 'https://stackoverflow.com/users/8574270/jordi'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "17\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526117872\n",
      "creation_date\n",
      "1525978587\n",
      "last_edit_date\n",
      "1525979672\n",
      "question_id\n",
      "50279749\n",
      "link\n",
      "https://stackoverflow.com/questions/50279749/python-3-5-replace-accent-by-html-entity\n",
      "title\n",
      "Python 3.5 replace accent by html entity\n",
      "tags\n",
      "['python', 'ubuntu', 'pip']\n",
      "owner\n",
      "{'reputation': 38, 'user_id': 3718183, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/0080bb0491c48f4b77c951f0da154cdb?s=128&d=identicon&r=PG&f=1', 'display_name': 'user3718183', 'link': 'https://stackoverflow.com/users/3718183/user3718183'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "12027\n",
      "accepted_answer_id\n",
      "34670459\n",
      "answer_count\n",
      "5\n",
      "score\n",
      "5\n",
      "last_activity_date\n",
      "1526117872\n",
      "creation_date\n",
      "1447570161\n",
      "last_edit_date\n",
      "1447572229\n",
      "question_id\n",
      "33717197\n",
      "link\n",
      "https://stackoverflow.com/questions/33717197/unable-to-install-python-pip-on-ubuntu-14-04\n",
      "title\n",
      "Unable to install python pip on Ubuntu 14.04\n",
      "tags\n",
      "['python', 'python-3.x']\n",
      "owner\n",
      "{'reputation': 6, 'user_id': 9779420, 'user_type': 'registered', 'profile_image': 'https://graph.facebook.com/211114726362390/picture?type=large', 'display_name': 'Vevina Liu', 'link': 'https://stackoverflow.com/users/9779420/vevina-liu'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "28\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526117816\n",
      "creation_date\n",
      "1526097487\n",
      "last_edit_date\n",
      "1526117816\n",
      "question_id\n",
      "50302705\n",
      "link\n",
      "https://stackoverflow.com/questions/50302705/how-to-winsorize-series-based-on-year-in-python\n",
      "title\n",
      "how to winsorize series based on year in python\n",
      "tags\n",
      "['python', 'web-scraping', 'scrapy']\n",
      "owner\n",
      "{'reputation': 906, 'user_id': 4544413, 'user_type': 'registered', 'accept_rate': 78, 'profile_image': 'https://www.gravatar.com/avatar/e76680e93b59e0f38238f5a0c47d1ca3?s=128&d=identicon&r=PG&f=1', 'display_name': 'Luis Ramon Ramirez Rodriguez', 'link': 'https://stackoverflow.com/users/4544413/luis-ramon-ramirez-rodriguez'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "14\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526117686\n",
      "creation_date\n",
      "1526090062\n",
      "question_id\n",
      "50302209\n",
      "link\n",
      "https://stackoverflow.com/questions/50302209/how-to-use-scrapy-loader-processors-for-long-functions\n",
      "title\n",
      "How to use scrapy loader processors for long functions?\n",
      "tags\n",
      "['python', 'python-2.7', 'pyinstaller']\n",
      "owner\n",
      "{'reputation': 6, 'user_id': 9779173, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/efcda2926e72f4d2d75e1dfa28b30437?s=128&d=identicon&r=PG&f=1', 'display_name': 'Mark C', 'link': 'https://stackoverflow.com/users/9779173/mark-c'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "22\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526117583\n",
      "creation_date\n",
      "1526090249\n",
      "last_edit_date\n",
      "1526117583\n",
      "question_id\n",
      "50302229\n",
      "link\n",
      "https://stackoverflow.com/questions/50302229/pyinstaller-not-finding-file-path-inside-program\n",
      "title\n",
      "pyinstaller not finding file path inside program\n",
      "tags\n",
      "['python', 'split']\n",
      "owner\n",
      "{'reputation': 10, 'user_id': 9548124, 'user_type': 'registered', 'profile_image': 'https://lh6.googleusercontent.com/-VUKE-avkV0o/AAAAAAAAAAI/AAAAAAAAAGc/siEYYXLjdCY/photo.jpg?sz=128', 'display_name': 'Sally Zeitler', 'link': 'https://stackoverflow.com/users/9548124/sally-zeitler'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "27\n",
      "accepted_answer_id\n",
      "50160213\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526117526\n",
      "creation_date\n",
      "1525364178\n",
      "last_edit_date\n",
      "1525364798\n",
      "question_id\n",
      "50159655\n",
      "link\n",
      "https://stackoverflow.com/questions/50159655/python-spliting-of-string-only-first-element-accessable\n",
      "title\n",
      "python spliting of string only first element accessable\n",
      "tags\n",
      "['python', 'recursion', 'turtle-graphics', 'fractals']\n",
      "owner\n",
      "{'reputation': 15, 'user_id': 8555198, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/e7f7f7cc1f9e9633c18abca42a6d5bc1?s=128&d=identicon&r=PG&f=1', 'display_name': 'rookie_senior', 'link': 'https://stackoverflow.com/users/8555198/rookie-senior'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "10\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526117511\n",
      "creation_date\n",
      "1526117143\n",
      "last_edit_date\n",
      "1526117511\n",
      "question_id\n",
      "50304718\n",
      "link\n",
      "https://stackoverflow.com/questions/50304718/varying-recursive-function-at-given-depth\n",
      "title\n",
      "Varying recursive function at given depth\n",
      "tags\n",
      "['python', 'python-3.x', 'python-2.7']\n",
      "owner\n",
      "{'reputation': 6, 'user_id': 9780061, 'user_type': 'registered', 'profile_image': 'https://lh5.googleusercontent.com/-2AkMcFH5kxg/AAAAAAAAAAI/AAAAAAAAADs/JOKV1hI34hA/photo.jpg?sz=128', 'display_name': 'Nin', 'link': 'https://stackoverflow.com/users/9780061/nin'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "23\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526117409\n",
      "creation_date\n",
      "1526116806\n",
      "question_id\n",
      "50304669\n",
      "link\n",
      "https://stackoverflow.com/questions/50304669/defining-list-from-a-function-with-multiple-arguments\n",
      "title\n",
      "Defining list from a function with multiple arguments\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tags\n",
      "['python', 'short']\n",
      "owner\n",
      "{'reputation': 3, 'user_id': 9682321, 'user_type': 'registered', 'profile_image': 'https://lh5.googleusercontent.com/-RdEoeNOcP2M/AAAAAAAAAAI/AAAAAAAAAaE/Boryoc0iBNA/photo.jpg?sz=128', 'display_name': 'Zach', 'link': 'https://stackoverflow.com/users/9682321/zach'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "19\n",
      "answer_count\n",
      "4\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526117198\n",
      "creation_date\n",
      "1526115651\n",
      "question_id\n",
      "50304518\n",
      "link\n",
      "https://stackoverflow.com/questions/50304518/how-to-print-two-numbers-from-the-same-list-in-python-2-7\n",
      "title\n",
      "How to print two numbers from the same list in Python 2.7\n",
      "tags\n",
      "['python', 'list', 'numpy', 'merge', 'masked-array']\n",
      "owner\n",
      "{'reputation': 125, 'user_id': 5688247, 'user_type': 'registered', 'accept_rate': 100, 'profile_image': 'https://i.stack.imgur.com/6YWTC.jpg?s=128&g=1', 'display_name': 'Jellyse', 'link': 'https://stackoverflow.com/users/5688247/jellyse'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "18\n",
      "accepted_answer_id\n",
      "50304662\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "2\n",
      "last_activity_date\n",
      "1526117088\n",
      "creation_date\n",
      "1526115127\n",
      "last_edit_date\n",
      "1526115677\n",
      "question_id\n",
      "50304457\n",
      "link\n",
      "https://stackoverflow.com/questions/50304457/merge-2d-list-of-masked-arrays-with-different-lengths\n",
      "title\n",
      "Merge 2D list of masked arrays with different lengths\n",
      "tags\n",
      "['python', 'regex', 'copy', 'paste', 'pyperclip']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 9582440, 'user_type': 'registered', 'profile_image': 'https://lh4.googleusercontent.com/-I77LuHNWehE/AAAAAAAAAAI/AAAAAAAAIV8/2tPqB44KeEQ/photo.jpg?sz=128', 'display_name': 'Kumar Ashwin', 'link': 'https://stackoverflow.com/users/9582440/kumar-ashwin'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "29\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "-1\n",
      "last_activity_date\n",
      "1526117051\n",
      "creation_date\n",
      "1526114083\n",
      "last_edit_date\n",
      "1526117051\n",
      "question_id\n",
      "50304323\n",
      "link\n",
      "https://stackoverflow.com/questions/50304323/regex-phone-and-email-extraction-output-error-python\n",
      "title\n",
      "Regex phone and email extraction output error - python\n",
      "tags\n",
      "['python', 'regex', 'substitution']\n",
      "owner\n",
      "{'reputation': 21, 'user_id': 4580566, 'user_type': 'registered', 'profile_image': 'https://i.stack.imgur.com/XwfdX.jpg?s=128&g=1', 'display_name': 'Lookcrabs', 'link': 'https://stackoverflow.com/users/4580566/lookcrabs'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "22\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526117003\n",
      "creation_date\n",
      "1526080186\n",
      "question_id\n",
      "50301358\n",
      "link\n",
      "https://stackoverflow.com/questions/50301358/python-string-template-substitution-with-dict-of-regex-groups\n",
      "title\n",
      "Python string template substitution with dict of regex groups?\n",
      "tags\n",
      "['python', 'bokeh']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 9751616, 'user_type': 'registered', 'profile_image': 'https://lh5.googleusercontent.com/-qN3Gi-6Rv6g/AAAAAAAAAAI/AAAAAAAAAGY/U4-ik0jY_IY/photo.jpg?sz=128', 'display_name': 'Jonas Bender', 'link': 'https://stackoverflow.com/users/9751616/jonas-bender'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "18\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526116947\n",
      "creation_date\n",
      "1525768299\n",
      "last_edit_date\n",
      "1526116947\n",
      "question_id\n",
      "50229287\n",
      "link\n",
      "https://stackoverflow.com/questions/50229287/bokeh-update-a-specific-list-in-column-with-a-slider\n",
      "title\n",
      "Bokeh update a specific list in column with a slider\n",
      "tags\n",
      "['python', 'string', 'concatenation', 'readlines']\n",
      "owner\n",
      "{'reputation': 62, 'user_id': 4147767, 'user_type': 'registered', 'accept_rate': 47, 'profile_image': 'https://www.gravatar.com/avatar/e20d2cd614df0b820c4b0389ed011783?s=128&d=identicon&r=PG&f=1', 'display_name': 'BabaSvoloch', 'link': 'https://stackoverflow.com/users/4147767/babasvoloch'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "16\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526116583\n",
      "creation_date\n",
      "1526116583\n",
      "question_id\n",
      "50304647\n",
      "link\n",
      "https://stackoverflow.com/questions/50304647/python-concatenate-string-from-file-with-string-literal\n",
      "title\n",
      "Python: concatenate string from file with string literal\n",
      "tags\n",
      "['python', 'google-assistant-sdk']\n",
      "owner\n",
      "{'reputation': 8, 'user_id': 9008990, 'user_type': 'registered', 'profile_image': 'https://lh4.googleusercontent.com/-ywfcHgaAzN4/AAAAAAAAAAI/AAAAAAAABuk/0w6wU7gd3ic/photo.jpg?sz=128', 'display_name': 'SudDaBuilder', 'link': 'https://stackoverflow.com/users/9008990/suddabuilder'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "314\n",
      "accepted_answer_id\n",
      "48900805\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526116508\n",
      "creation_date\n",
      "1519110645\n",
      "last_edit_date\n",
      "1519196362\n",
      "question_id\n",
      "48879645\n",
      "link\n",
      "https://stackoverflow.com/questions/48879645/unable-to-register-google-assistant-device-model\n",
      "title\n",
      "Unable to register Google Assistant Device Model\n",
      "tags\n",
      "['python', 'pprint']\n",
      "owner\n",
      "{'reputation': 5, 'user_id': 9135962, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/13d13ad7254a4d426ce0141c03e5d207?s=128&d=identicon&r=PG&f=1', 'display_name': 'Zhao Canxiang', 'link': 'https://stackoverflow.com/users/9135962/zhao-canxiang'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "22\n",
      "accepted_answer_id\n",
      "50304586\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526116443\n",
      "creation_date\n",
      "1526115386\n",
      "question_id\n",
      "50304483\n",
      "link\n",
      "https://stackoverflow.com/questions/50304483/python3-6-5-pprint-a-list-error\n",
      "title\n",
      "python3.6.5 pprint a list error\n",
      "tags\n",
      "['python']\n",
      "owner\n",
      "{'reputation': 91, 'user_id': 2921962, 'user_type': 'registered', 'profile_image': 'https://i.stack.imgur.com/53hUw.png?s=128&g=1', 'display_name': 'spacegame', 'link': 'https://stackoverflow.com/users/2921962/spacegame'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "24438\n",
      "accepted_answer_id\n",
      "19602014\n",
      "answer_count\n",
      "12\n",
      "score\n",
      "8\n",
      "last_activity_date\n",
      "1526116429\n",
      "creation_date\n",
      "1382751783\n",
      "last_edit_date\n",
      "1434952766\n",
      "question_id\n",
      "19601903\n",
      "link\n",
      "https://stackoverflow.com/questions/19601903/find-the-longest-substring-in-alphabetical-order\n",
      "title\n",
      "Find the longest substring in alphabetical order\n",
      "tags\n",
      "['python', 'pandas', 'parsing']\n",
      "owner\n",
      "{'reputation': 128, 'user_id': 3528391, 'user_type': 'registered', 'accept_rate': 100, 'profile_image': 'https://www.gravatar.com/avatar/c890cad236805e82d4e6eede2ba9869f?s=128&d=identicon&r=PG&f=1', 'display_name': 'nightmarish', 'link': 'https://stackoverflow.com/users/3528391/nightmarish'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "106\n",
      "accepted_answer_id\n",
      "47945396\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526116375\n",
      "creation_date\n",
      "1513963146\n",
      "question_id\n",
      "47945145\n",
      "link\n",
      "https://stackoverflow.com/questions/47945145/unicodedecodeerror-when-reading-a-dataset-from-a-webpage-into-a-pandas-dataframe\n",
      "title\n",
      "UnicodeDecodeError when reading a dataset from a webpage into a Pandas dataframe\n",
      "tags\n",
      "['python', 'dictionary', 'list-comprehension', 'dictionary-comprehension']\n",
      "owner\n",
      "{'reputation': 11, 'user_id': 4537657, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/913e4e40f7066d058c78d61a12969207?s=128&d=identicon&r=PG&f=1', 'display_name': 'giltrapo', 'link': 'https://stackoverflow.com/users/4537657/giltrapo'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "51\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526116309\n",
      "creation_date\n",
      "1509006700\n",
      "last_edit_date\n",
      "1509007526\n",
      "question_id\n",
      "46949380\n",
      "link\n",
      "https://stackoverflow.com/questions/46949380/filter-python-dictionary-with-dictionary-comprehension\n",
      "title\n",
      "Filter python dictionary with dictionary-comprehension\n",
      "tags\n",
      "['python', 'django', 'postgresql', 'autofield']\n",
      "owner\n",
      "{'reputation': 443, 'user_id': 8495108, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/251885f62e04029b88083ab655a9b55d?s=128&d=identicon&r=PG&f=1', 'display_name': 'Chiefir', 'link': 'https://stackoverflow.com/users/8495108/chiefir'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "34\n",
      "accepted_answer_id\n",
      "50139055\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "2\n",
      "last_activity_date\n",
      "1526116246\n",
      "creation_date\n",
      "1525274965\n",
      "last_edit_date\n",
      "1525277679\n",
      "question_id\n",
      "50138330\n",
      "link\n",
      "https://stackoverflow.com/questions/50138330/integrityerror-after-table-restore-from-backup-postgresql-django\n",
      "title\n",
      "IntegrityError after table restore from backup, PostgreSQL + Django\n",
      "tags\n",
      "['python']\n",
      "owner\n",
      "{'reputation': 88, 'user_id': 5108490, 'user_type': 'registered', 'accept_rate': 45, 'profile_image': 'https://www.gravatar.com/avatar/4922f61b3bbeb302b875be247c6dcae5?s=128&d=identicon&r=PG&f=1', 'display_name': 'cyberoy', 'link': 'https://stackoverflow.com/users/5108490/cyberoy'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "2979\n",
      "answer_count\n",
      "3\n",
      "score\n",
      "2\n",
      "last_activity_date\n",
      "1526115884\n",
      "creation_date\n",
      "1436723586\n",
      "question_id\n",
      "31370809\n",
      "link\n",
      "https://stackoverflow.com/questions/31370809/count-the-number-of-characters-in-each-line\n",
      "title\n",
      "Count the number of characters in each line\n",
      "tags\n",
      "['python', 'r', 'python-import']\n",
      "owner\n",
      "{'reputation': 136, 'user_id': 8165879, 'user_type': 'registered', 'accept_rate': 77, 'profile_image': 'https://www.gravatar.com/avatar/bcfba5b4fd0c2b845d9990e4f2f396b2?s=128&d=identicon&r=PG&f=1', 'display_name': 'Yash', 'link': 'https://stackoverflow.com/users/8165879/yash'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "24\n",
      "closed_date\n",
      "1526068194\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526115880\n",
      "creation_date\n",
      "1526046623\n",
      "last_edit_date\n",
      "1526115880\n",
      "question_id\n",
      "50293850\n",
      "link\n",
      "https://stackoverflow.com/questions/50293850/importing-your-r-module-in-python-scripts\n",
      "closed_reason\n",
      "off-topic\n",
      "title\n",
      "Importing your R module in python scripts\n",
      "tags\n",
      "['python', 'dataframe', 'pyspark', 'spark-dataframe']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 8993373, 'user_type': 'registered', 'profile_image': 'https://lh5.googleusercontent.com/-fn4NwARLBTo/AAAAAAAAAAI/AAAAAAAAABo/Tqn4HVBmVGY/photo.jpg?sz=128', 'display_name': 'ZMGhodsi', 'link': 'https://stackoverflow.com/users/8993373/zmghodsi'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "16\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526115878\n",
      "creation_date\n",
      "1526104571\n",
      "last_edit_date\n",
      "1526110372\n",
      "question_id\n",
      "50303307\n",
      "link\n",
      "https://stackoverflow.com/questions/50303307/spark-grouped-dataframe-details\n",
      "title\n",
      "Spark grouped Dataframe details\n",
      "tags\n",
      "['python', 'python-3.x', 'atom-editor', 'hydrogen']\n",
      "owner\n",
      "{'reputation': 11, 'user_id': 8559730, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/a319a78bc7547a46dcfe50a397e2b96c?s=128&d=identicon&r=PG&f=1', 'display_name': 'ExpertShaun', 'link': 'https://stackoverflow.com/users/8559730/expertshaun'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "11\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526115671\n",
      "creation_date\n",
      "1526115671\n",
      "question_id\n",
      "50304519\n",
      "link\n",
      "https://stackoverflow.com/questions/50304519/using-hydrongen-with-python-3\n",
      "title\n",
      "Using Hydrongen with Python 3\n",
      "tags\n",
      "['python', 'ctypes']\n",
      "owner\n",
      "{'reputation': 103, 'user_id': 4676162, 'user_type': 'registered', 'accept_rate': 53, 'profile_image': 'https://www.gravatar.com/avatar/f2a8ed16c6167eb66ef2285ecb61c14e?s=128&d=identicon&r=PG&f=1', 'display_name': 'Sir DrinksCoffeeALot', 'link': 'https://stackoverflow.com/users/4676162/sir-drinkscoffeealot'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "7\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526115647\n",
      "creation_date\n",
      "1526115647\n",
      "question_id\n",
      "50304516\n",
      "link\n",
      "https://stackoverflow.com/questions/50304516/getting-elements-from-ctype-structure-with-introspection\n",
      "title\n",
      "Getting elements from ctype structure with introspection?\n",
      "tags\n",
      "['python', 'function']\n",
      "owner\n",
      "{'reputation': 6, 'user_id': 7122649, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/542a7fece1e6ee55884daf197c3a1326?s=128&d=identicon&r=PG&f=1', 'display_name': 'base10', 'link': 'https://stackoverflow.com/users/7122649/base10'}\n",
      "is_answered\n",
      "True\n",
      "view_count\n",
      "24\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526115620\n",
      "creation_date\n",
      "1526114513\n",
      "question_id\n",
      "50304376\n",
      "link\n",
      "https://stackoverflow.com/questions/50304376/executing-a-function-base-on-a-condition\n",
      "title\n",
      "Executing a function base on a condition\n",
      "tags\n",
      "['python', 'cryptography', 'bitcoin', 'ecdsa']\n",
      "owner\n",
      "{'reputation': 674, 'user_id': 529181, 'user_type': 'registered', 'accept_rate': 72, 'profile_image': 'https://www.gravatar.com/avatar/64c126dcff01331adb2471337c05ba10?s=128&d=identicon&r=PG', 'display_name': 'zrbecker', 'link': 'https://stackoverflow.com/users/529181/zrbecker'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "5\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526115603\n",
      "creation_date\n",
      "1526115603\n",
      "question_id\n",
      "50304509\n",
      "link\n",
      "https://stackoverflow.com/questions/50304509/is-python-ecdsa-signature-size-correct\n",
      "title\n",
      "Is python-ecdsa signature size correct?\n",
      "tags\n",
      "['python', 'linux']\n",
      "owner\n",
      "{'reputation': 106, 'user_id': 2899096, 'user_type': 'registered', 'accept_rate': 55, 'profile_image': 'https://www.gravatar.com/avatar/2d2e0bdf39b82e42289cf23ab4cc4813?s=128&d=identicon&r=PG&f=1', 'display_name': 'omer mazig', 'link': 'https://stackoverflow.com/users/2899096/omer-mazig'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "524\n",
      "answer_count\n",
      "2\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526115434\n",
      "creation_date\n",
      "1525618206\n",
      "question_id\n",
      "50201005\n",
      "link\n",
      "https://stackoverflow.com/questions/50201005/python-error-importerror-cannot-import-name-dist\n",
      "title\n",
      "Python error - &quot;ImportError: cannot import name &#39;dist&#39;&quot;\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tags\n",
      "['python', 'pandas', 'csv', 'bigdata', 'export-to-csv']\n",
      "owner\n",
      "{'reputation': 58, 'user_id': 6326148, 'user_type': 'registered', 'accept_rate': 89, 'profile_image': 'https://www.gravatar.com/avatar/8e59946b16c9d154be72b75dbbdd0701?s=128&d=identicon&r=PG&f=1', 'display_name': 'Miha', 'link': 'https://stackoverflow.com/users/6326148/miha'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "15\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526115419\n",
      "creation_date\n",
      "1526115004\n",
      "question_id\n",
      "50304435\n",
      "link\n",
      "https://stackoverflow.com/questions/50304435/how-to-create-csv-file-bigger-than-you-ram-using-python-and-pandas\n",
      "title\n",
      "How to create csv file bigger than you RAM using Python and Pandas\n",
      "tags\n",
      "['python', 'exception', 'flask', 'exception-handling', 'sentry']\n",
      "owner\n",
      "{'reputation': 4465, 'user_id': 400745, 'user_type': 'registered', 'accept_rate': 79, 'profile_image': 'https://i.stack.imgur.com/qIDSJ.jpg?s=128&g=1', 'display_name': 'valk', 'link': 'https://stackoverflow.com/users/400745/valk'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "38\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "-1\n",
      "last_activity_date\n",
      "1526115294\n",
      "creation_date\n",
      "1526112839\n",
      "last_edit_date\n",
      "1526115294\n",
      "question_id\n",
      "50304183\n",
      "link\n",
      "https://stackoverflow.com/questions/50304183/catch-all-python-exception-in-one-method\n",
      "title\n",
      "Catch all Python exception in one method\n",
      "tags\n",
      "['python', 'numpy', 'for-loop', 'memory-leaks']\n",
      "owner\n",
      "{'reputation': 43, 'user_id': 2279682, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/88cf3e22a395cd54155bd18abb589bc5?s=128&d=identicon&r=PG', 'display_name': 'Lara Larsen', 'link': 'https://stackoverflow.com/users/2279682/lara-larsen'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "17\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526115236\n",
      "creation_date\n",
      "1526113691\n",
      "last_edit_date\n",
      "1526115236\n",
      "question_id\n",
      "50304272\n",
      "link\n",
      "https://stackoverflow.com/questions/50304272/python-numpy-memory-leak-inside-loop\n",
      "title\n",
      "python numpy memory leak inside loop\n",
      "tags\n",
      "['python', 'outlook', 'win32com']\n",
      "owner\n",
      "{'reputation': 46, 'user_id': 6950894, 'user_type': 'registered', 'accept_rate': 81, 'profile_image': 'https://www.gravatar.com/avatar/0b1ed0d494fd3b3522d8ac802faa8d15?s=128&d=identicon&r=PG&f=1', 'display_name': 'Dantuzzo', 'link': 'https://stackoverflow.com/users/6950894/dantuzzo'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "7\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526115146\n",
      "creation_date\n",
      "1526115146\n",
      "question_id\n",
      "50304459\n",
      "link\n",
      "https://stackoverflow.com/questions/50304459/python-saving-outlook-message-as-msg-file\n",
      "title\n",
      "Python: Saving Outlook message as .msg file\n",
      "tags\n",
      "['python', 'apache-spark', 'dataframe', 'pyspark', 'spark-dataframe']\n",
      "owner\n",
      "{'reputation': 32, 'user_id': 9172344, 'user_type': 'registered', 'profile_image': 'https://lh6.googleusercontent.com/-qw9GSK-15dg/AAAAAAAAAAI/AAAAAAAAAAg/SDYtB7_UN40/photo.jpg?sz=128', 'display_name': 'Zhang Xin', 'link': 'https://stackoverflow.com/users/9172344/zhang-xin'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "59\n",
      "answer_count\n",
      "1\n",
      "score\n",
      "2\n",
      "last_activity_date\n",
      "1526115121\n",
      "creation_date\n",
      "1526010957\n",
      "last_edit_date\n",
      "1526115121\n",
      "question_id\n",
      "50284760\n",
      "link\n",
      "https://stackoverflow.com/questions/50284760/how-to-assign-a-string-variable-to-a-dataframe-name\n",
      "title\n",
      "How to assign a String variable to a dataframe name\n",
      "tags\n",
      "['python']\n",
      "owner\n",
      "{'reputation': 6, 'user_id': 9763349, 'user_type': 'registered', 'profile_image': 'https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=128', 'display_name': 'symon dhilip', 'link': 'https://stackoverflow.com/users/9763349/symon-dhilip'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "38\n",
      "answer_count\n",
      "4\n",
      "score\n",
      "1\n",
      "last_activity_date\n",
      "1526115119\n",
      "creation_date\n",
      "1526113144\n",
      "last_edit_date\n",
      "1526113237\n",
      "question_id\n",
      "50304216\n",
      "link\n",
      "https://stackoverflow.com/questions/50304216/to-split-and-save-text-in-a-file-using-python\n",
      "title\n",
      "To split and save text in a file using python\n",
      "tags\n",
      "['java', 'python', 'python-3.x', 'sockets', 'rabbitmq']\n",
      "owner\n",
      "{'reputation': 4, 'user_id': 8168791, 'user_type': 'registered', 'profile_image': 'https://graph.facebook.com/1685691695074031/picture?type=large', 'display_name': 'Marcos Ayala', 'link': 'https://stackoverflow.com/users/8168791/marcos-ayala'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "13\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526114857\n",
      "creation_date\n",
      "1526053539\n",
      "last_edit_date\n",
      "1526070101\n",
      "question_id\n",
      "50295860\n",
      "link\n",
      "https://stackoverflow.com/questions/50295860/rabbitmq-or-sockets-to-send-a-json-file-from-a-java-applicatio-to-python-applica\n",
      "title\n",
      "RabbitMQ or sockets to send a json file from a java applicatio to python application?\n",
      "tags\n",
      "['python', 'datetime', 'youtube-api', 'datetime-format']\n",
      "owner\n",
      "{'reputation': 7248, 'user_id': 604388, 'user_type': 'registered', 'accept_rate': 75, 'profile_image': 'https://www.gravatar.com/avatar/dfdf62e565f166f68c6772d96f6523e1?s=128&d=identicon&r=PG', 'display_name': 'LA_', 'link': 'https://stackoverflow.com/users/604388/la'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "8\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526114841\n",
      "creation_date\n",
      "1526114841\n",
      "question_id\n",
      "50304415\n",
      "link\n",
      "https://stackoverflow.com/questions/50304415/how-to-get-date-in-correct-format-for-youtube-upload\n",
      "title\n",
      "How to get date in correct format for YouTube upload?\n",
      "tags\n",
      "['python', 'python-3.x', 'jupyter-notebook']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 9780008, 'user_type': 'registered', 'profile_image': 'https://lh3.googleusercontent.com/-2GtBro0C2Eg/AAAAAAAAAAI/AAAAAAAAAuE/-TqAwbeRkW0/photo.jpg?sz=128', 'display_name': 'Ram Varun', 'link': 'https://stackoverflow.com/users/9780008/ram-varun'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "18\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "-2\n",
      "last_activity_date\n",
      "1526114837\n",
      "creation_date\n",
      "1526114689\n",
      "last_edit_date\n",
      "1526114837\n",
      "question_id\n",
      "50304397\n",
      "link\n",
      "https://stackoverflow.com/questions/50304397/indexerror-list-index-out-of-range-in-my-code\n",
      "title\n",
      "IndexError: list index out of range in my code\n",
      "tags\n",
      "['python', 'scikit-learn', 'svm', 'grid-search', 'hyperparameters']\n",
      "owner\n",
      "{'reputation': 1, 'user_id': 8866884, 'user_type': 'registered', 'profile_image': 'https://www.gravatar.com/avatar/429ca19545d9da9570f7afea97d15706?s=128&d=identicon&r=PG&f=1', 'display_name': 'DexzMen', 'link': 'https://stackoverflow.com/users/8866884/dexzmen'}\n",
      "is_answered\n",
      "False\n",
      "view_count\n",
      "8\n",
      "answer_count\n",
      "0\n",
      "score\n",
      "0\n",
      "last_activity_date\n",
      "1526114737\n",
      "creation_date\n",
      "1526113835\n",
      "last_edit_date\n",
      "1526114737\n",
      "question_id\n",
      "50304293\n",
      "link\n",
      "https://stackoverflow.com/questions/50304293/paralleled-cross-validation-for-groups-of-hyperparameters-in-python\n",
      "title\n",
      "Paralleled cross validation for groups of hyperparameters in python\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: []\n",
       "Index: []"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests, json\n",
    "import pandas as pd\n",
    "def buildUrl(page, pagesize, tagged):\n",
    "    return 'https://api.stackexchange.com/2.2/questions?order=desc&sort=activity&site=stackoverflow&page={0}&pagesize={1}&tagged={2}'.format(page, pagesize, tagged)\n",
    "\n",
    "pagesize = 20\n",
    "tagged = 'python'\n",
    "linesQuan = 50\n",
    "has_more = True\n",
    "page = 1\n",
    "lines = 0\n",
    "\n",
    "frame = pd.DataFrame()\n",
    "ser = pd.Series()\n",
    "\n",
    "while (lines <= linesQuan and has_more):\n",
    "    result = requests.get(buildUrl(page, pagesize, tagged))\n",
    "    if result.status_code != 200:\n",
    "         break\n",
    "    else :     \n",
    "        for key in result.json().get('items'):\n",
    "            if lines < linesQuan:\n",
    "                for i, itKeys  in enumerate(key.keys()):\n",
    "                   # if(itKeys) != \"owner\":\n",
    "                   #     frame[itKeys] = key[itKeys]\n",
    "                    print(itKeys)\n",
    "                    print(key[itKeys])\n",
    "                #frame = frame.append(pd.Series([key]), ignore_index=True)\n",
    "            lines = lines + 1\n",
    "        has_more = result.json().get('has_more')               \n",
    "        page = page + 1\n",
    "     \n",
    "        \n",
    "frame.head(linesQuan)   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "my cool string: Hello there!\n"
     ]
    }
   ],
   "source": [
    "url = 'https://api.stackexchange.com/2.2/questions?order=desc&sort=activity&site=stackoverflow'\n",
    "url = url + \"&page={0}\", \"&pagesize={1}\" \n",
    "url.format())\n",
    "print(\"my {0} string: {1}\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests, json\n",
    "import pandas as pd\n",
    "url = 'https://api.stackexchange.com/2.2/questions?order=desc&sort=activity&site=stackoverflow'\n",
    "pagesize = 10\n",
    "tagged = 'python'\n",
    "linesQuan = 20\n",
    "has_more = True\n",
    "page = 1\n",
    "lines = 0\n",
    "error = False\n",
    "frame = pd.DataFrame()\n",
    "#ser = pd.Series()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n"
     ]
    }
   ],
   "source": [
    "\n",
    "while (lines <= linesQuan and has_more and not error):\n",
    "    payload = {'page': page, 'pagesize': pagesize, 'tagged': tagged}\n",
    "    result =requests.get(url, params=payload)\n",
    "    if result.status_code == 200:\n",
    "        for key in result.json().get('items'):\n",
    "            if lines < linesQuan:\n",
    "                frame = frame.append(pd.Series([key['title']]), ignore_index=True)\n",
    "            lines = lines + 1\n",
    "        has_more = result.json().get('has_more')               \n",
    "        page = page + 1\n",
    "    else : \n",
    "        error = True\n",
    "        break\n",
    " \n",
    "print(type(frame))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "url: https://api.stackexchange.com/2.2/questions?order=desc&sort=activity&site=stackoverflow\n",
      "pagesize: 10\n",
      "tagged: python\n",
      "lines quantity: 30\n",
      "Tensorflow outputs additional unexpected result\n",
      "ImportError: cannot import name _imagingtk\n",
      "python pygame key held down\n",
      "Python syntax error with &quot;\n",
      "Writing nested lists to json\n",
      "Get user id and user name from balebot\n",
      "Forecast the remaining time of a loop\n",
      "Reading full packet using python raw socket\n",
      "Update flask without refresh\n",
      "&#39;import module&#39; or &#39;from module import&#39;\n",
      "What is leaf_values from Python LightGBM?\n",
      "&quot;Checkbord-like&quot; binary selection\n",
      "Compile (but do not run) a Python script\n",
      "matplotlib error - no module named tkinter\n",
      "Driving Duration and Distance - Python\n",
      "pip install fails for all the packages\n",
      "PyCrypto: function returned by the decrypt() method\n",
      "SMOTE Over-sampling technique\n",
      "Transform pyspark dataframe row value as a relation of other elements in the same row\n",
      "Why utf8mb4 on mysql DB, Table, column gives error on inserting special characters?\n",
      "How to increment for loop index when used with range in python?\n",
      "AttributeError: &#39;numpy.ndarray&#39; object has no attribute &#39;convert&#39; and error of IndexError: list index out of range\n",
      "How can I replace the stem word sentence in pandas.Series?\n",
      "How can i check if an inputted variable either starts with &quot;Q&quot; or it is a number\n",
      "How to write text on a image in windows using python opencv2\n",
      "Issue with MultiProcessing in Python with BeautifulSoup 4\n",
      "Django - show the query in the search box on the results page\n",
      "Calculate randomly integers within a range in python\n",
      "How to get a website&#39;s body width with selenium and python?\n",
      "How can i change a field with numbers and letters to just numbers in python\n"
     ]
    }
   ],
   "source": [
    "import requests, json\n",
    "url = input('url: ')\n",
    "pagesize = input('pagesize: ')\n",
    "tagged = input('tagged: ')\n",
    "linesQuan = int(input('lines quantity: '))\n",
    "has_more = True\n",
    "page = 1\n",
    "lines = 0\n",
    "error = False\n",
    "while (lines <= linesQuan and has_more and not error):\n",
    "    payload = {'page': page, 'pagesize': pagesize, 'tagged': tagged}\n",
    "    result =requests.get(url, params=payload)\n",
    "    if result.status_code == 200:\n",
    "        for key in result.json().get('items'):\n",
    "            if lines < linesQuan:\n",
    "                print(key['title'])\n",
    "            lines = lines + 1\n",
    "        has_more = result.json().get('has_more')               \n",
    "        page = page + 1\n",
    "    else : \n",
    "        error = True\n",
    "        break\n",
    "print('end')  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "the JSON object must be str, bytes or bytearray, not 'dict'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-4-92e2e07e8747>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0murl\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34m'https://api.stackexchange.com/2.2/questions?pagesize=20&order=desc&sort=activity&tagged=python&site=stackoverflow'\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mrequests\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0murl\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 5\u001b[1;33m \u001b[0mparsed_string\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mjson\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mloads\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mresult\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mjson\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      6\u001b[0m \u001b[1;31m#for key in result.json().get('items'):\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mc:\\users\\daniel and tanya\\appdata\\local\\programs\\python\\python36-32\\lib\\json\\__init__.py\u001b[0m in \u001b[0;36mloads\u001b[1;34m(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)\u001b[0m\n\u001b[0;32m    346\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0misinstance\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0ms\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mbytes\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbytearray\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    347\u001b[0m             raise TypeError('the JSON object must be str, bytes or bytearray, '\n\u001b[1;32m--> 348\u001b[1;33m                             'not {!r}'.format(s.__class__.__name__))\n\u001b[0m\u001b[0;32m    349\u001b[0m         \u001b[0ms\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0ms\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdecode\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdetect_encoding\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0ms\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m'surrogatepass'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    350\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTypeError\u001b[0m: the JSON object must be str, bytes or bytearray, not 'dict'"
     ]
    }
   ],
   "source": [
    "import requests, json\n",
    "\n",
    "url = 'https://api.stackexchange.com/2.2/questions?pagesize=20&order=desc&sort=activity&tagged=python&site=stackoverflow'\n",
    "result = requests.get(url)\n",
    "parsed_string = json.loads(result.json())\n",
    "#for key in result.json().get('items'):\n",
    "    \n",
    "\n",
    "print(parsed_string)\n",
    "\n",
    "#for key in title.get('items')[i]:\n",
    "#        if key == 'title':\n",
    "#            print(title['items'][i][key]) "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
